### ISSUE TITLE
Feature request: upload of deck's cover

### ISSUE THREAD

**Issue by marccarre** [floscha/tinycards-python-api#47]
### Description

It is currently **not** possible to create decks with cover images.

Supporting this feature would allow covers to be set programmatically, instead of having to set these manually once the decks are created via `tinycards-python-api`.

### Current state
 
Currently, `Deck`'s `cover` argument is simply ignored:
https://github.com/floscha/tinycards-python-api/blob/cf8f5fc08fb3d5746719eb91c3c6fad8bdadecaa/tinycards/model/deck.py#L9-L29
And even though there is logic to handle `imageFile` in `to_multipart_form`, no value is actually provided:
https://github.com/floscha/tinycards-python-api/blob/0103a53b8393942efcf82b7dd6fb852b00b70686/tinycards/networking/form_utils.py#L15-L22

**Comment by floscha** [comment]
Hi @marccarre, thanks for your request.

I agree that supporting deck covers would be a great addition to the library. However, I'm not really using them personally and also nobody else requested this feature so far. But you're very welcome to create a pull request to add the desired functionality. Otherwise, I'll see if I can find some time on the weekend to do it myself.

**Comment by marccarre** [comment]
@floscha, thanks for your reply 🙂 
I've just opened a PR (#49), please let me know your thoughts.
