### ISSUE TITLE
More intuitive Deck properties

### ISSUE THREAD

**Issue by floscha** [floscha/tinycards-python-api#60]
As hinted in #57, I believe some properties of the `Deck` class which are taken straight from Tinycards' internal JSON schema, are rather unintuitive for users not familiar with this schema. Instead, the properties could be based on the **Deck Settings** dialog of Tinycards' web UI, shown in the screenshot below:
<img width="300" alt="Screen Shot 2019-03-17 at 18 05 08" src="https://user-images.githubusercontent.com/33159547/54494917-6b807b80-48df-11e9-8ef6-f5424e93fc06.png">

To start with, I suggest the following properties to be replaced (the intended bullets are the suggested replacements):
- `blacklisted_side_indices` can be set to the indices 0 or 1.
    - `quiz_learners_on` would take one of the following values: `both sides` (default), `front only`, `back only`. Optionally the string could be lowercased to also enable inputs exactly like they appear in the UI, e.g. `Both sides`.
- `blacklisted_question_types` is currently a rather over-complicated list of lists of string constants (`ASSISTED_PRODUCTION` or `PRODUCTION`) that are quite hard to make sense of by themselves.
    - `enable typing questions` could simply be a boolean. The downside of this simplification is that it is global and cannot have different values for front and back sides. However this feature is also not available in the Tinycards UI (to my knowledge at least), so it's debatable wether or not this option should actually exist. 
- `grading_modes` is a list of string constants (`'NO_TYPOS` or nothing).
    - `allow typos in responses` could also just be a boolean.

Additionally, the `tts_languages` property could accept not only the language codes (which many I believe have to look up), but instead also the full name of the language, again internally lowercased to e.g. accept both `English` and `english`.

In the end, I believe this issue comes down to a design choice whether the Python API should be closer to the web UI or the internal JSON representations. While the `tts_languages` property could accept both languages codes as well as the full names, the other properties seem more mutual exclusive. @marccarre do you have an opinion on this?

**Comment by marccarre** [comment]
I don't have any strong opinion, but I believe the issue is that `Deck` currently mixes two responsibilities. It is both:

- a "[DTO](https://en.wikipedia.org/wiki/Data_transfer_object)" between Tinycards' API and `tinycards-python-api`,
- a higher-level "[model](https://en.wikipedia.org/wiki/Business_logic#Business_logic_layer)" object between `tinycards-python-api` and end-users,

which makes it difficult for _both_ end-users and maintainers.

I think it could indeed maybe be better to separate these responsibilities more clearly, and have:
- a lower-level class which matches the internal JSON representations perfectly, and
- a higher-level class which is nicer to use, less cryptic, and closer to [tinycards.duolingo.com](https://tinycards.duolingo.com)'s UI.

That way, should Tinycards add new options that the high-level API doesn't expose yet, an advanced developer could always use the lower-level classes to hack his way around in order to make things work.
And that way, changes to the lower-level API would break/change the "contract" between `tinycards-python-api` and its end-users.

Note that the lower-level API could be a really thin layer heavily leveraging `json.loads`/`json/dumps`, not having _snake_cased_ attributes, but `camelCased` ones to match the expected JSON more closely (or could be using a method to automatically convert from one to the other, if strong opinion and/or too much eyebleed). Effectively, it should simplify [`json_converter.py`](https://github.com/floscha/tinycards-python-api/blob/master/tinycards/networking/json_converter.py) and make it more accessible to the end-user (while, paradoxically still hiding it a bit). Logic from the [`networking`](https://github.com/floscha/tinycards-python-api/tree/master/tinycards/networking) package would only interact with the lower-level API and not with `Deck` as it currently does. `Deck` would only expose higher-level options (but all of them). Either `Deck` or the deck DTO or utility functions could translate from higher-level to lower-level, and back. Such a design should hopefully avoid the kind of dilemma we had with `cover`/`imageUrl`/`coverImageUrl`, limit chances of bugs/oddities in the behaviour, etc. while still being nicer to use for the end-user.

`</2cents>` 
Hope this helps 🤷‍♂️

**Comment by floscha** [comment]
Since Tinycards has been [disabled by Duolingo](https://support.duolingo.com/hc/en-us/articles/360043909772-UPDATE-Tinycards-Announcement) on September 1, 2020, this repository will no longer be maintained.
