### ISSUE TITLE
Import/Export Decks using JSON

### ISSUE THREAD

**Issue by newbiemate** [floscha/tinycards-python-api#70]
It would be nice to be able to import and export decks using JSON. This would allow easy editing in any text editor we like, and also allow cross-compability with other tools when exporting.

**Comment by floscha** [comment]
Hi @newbiemate. Thanks for the suggestion and sorry for the late reply.

Would you expect the JSON import/export to be done using the command line? Because this can already be done quite easily using the Python API as the *json_converter.py* module provides all the functionality that you need.

So, if you prefer the command line, I can add the import/export functionality there. Or if you prefer Python, I could also add a quick example that shows how to import/export JSON data.

**Comment by floscha** [comment]
Since Tinycards has been [disabled by Duolingo](https://support.duolingo.com/hc/en-us/articles/360043909772-UPDATE-Tinycards-Announcement) on September 1, 2020, this repository will no longer be maintained.
